name: Flutter Build Project
on: [push, pull_request]
jobs:
  Build-Project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
          cache: true
          cache-key: flutter
          
      - run: flutter --version
      - run: ls -al
      - run: flutter pub get
      # - run: flutter test   # enable again once tests have been written
      - run: flutter build apk
